import { Inter } from "next/font/google";
import "./globals.css";
import { getServerSession } from "next-auth"
import SessionProvider from "./components/utils/SessionProvider"
import Header from "@/app/components/layouts/Header/Header";



const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const session = await getServerSession()
  return (
    <html lang="en">
      <body>
        <SessionProvider session={session}>
          <Header />
          {children}
        </SessionProvider>
      </body>
    </html>
  );
}
